/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.una.graphic;

/**
 *
 * @author Victor-Ayala
 */
public class ConsultaCamaUTI extends javax.swing.JPanel {

    /**
     * Creates new form Consulta
     */
    public ConsultaCamaUTI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        labelConsulta = new javax.swing.JLabel();
        panelTabla = new javax.swing.JPanel();
        scrollTabla = new javax.swing.JScrollPane();
        tablaConsulta = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        labelConsulta.setFont(new java.awt.Font("Segoe UI", 2, 36)); // NOI18N
        labelConsulta.setText("CONSULTA");
        panelTitulo.add(labelConsulta);

        add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelTabla.setLayout(new java.awt.BorderLayout());

        tablaConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "HOSPITAL", "CAMA", "ESTADO"
            }
        ));
        scrollTabla.setViewportView(tablaConsulta);

        panelTabla.add(scrollTabla, java.awt.BorderLayout.CENTER);

        add(panelTabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelConsulta;
    private javax.swing.JPanel panelTabla;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollTabla;
    private javax.swing.JTable tablaConsulta;
    // End of variables declaration//GEN-END:variables
}
